version: '3.7'

services:
  static-server:
    container_name: cross_domains_script
    image: halverneus/static-file-server:latest
    volumes:
      - ./dist:/web
    environment:
      - CORS=true
      - FOLDER=/web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-server-cross-domains-header.rule=Host(`example.com`) && PathPrefix(`/cross-domains-header/`)"
      - "traefik.http.routers.static-server-cross-domains-header.entrypoints=websecure"
      - "traefik.http.routers.static-server-cross-domains-header.tls.certresolver=mytlschallenge"
    networks:
      - my_network

networks:
  my_network:
    external: true
